config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :message,  presence: true, length:{maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    
  def index
    @tweets = Tweet.all
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    tweet = Tweet.new(message: params[:tweet][:message],tdate: params[:tweet][:tdate])
    if tweet.save
     redirect_to root_path
    else
     flash[:notice] = "エラー"
     redirect_to new_tweet_path
    end
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end
  
  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    message= params[:tweet][:message]
    tdate = params[:tweet][:message]
    @tweet = Tweet.find(params[:id])
    @tweet.update(message: message, tdate: tdate)
    if @tweet.save
      flash[:notice] = "1 record update"
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp1</title>
    <%= csrf_meta_tags %>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="style.css"> 
        <body bgcolor=white>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
    <div id="container">
        <div id="header">
            <%= render "header" %>
        </div>
        <div id="sidebar">
            <%= render "sidebar" %>
        </div>
        <div id="content">
            <%= yield %>
        </div>
        <div id="footer">
            <%= render "footer" %>
        </div>
    </div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= f.label :message, 'メッセージ' %>
<%= f.text_field :message %>
<% @tweet.tdate = @tweet.tdate %>
<%= f.hidden_field :tdate %>

<%= f.submit '更新' %>

app/views/tweets/_header.html.erb
<img src="assets/b.png" alt="header" height="140" width="100%" align="top">

app/views/tweets/_sidebar.html.erb
<p class="trim-image-to-circle"></p>
<h1>ユーザー</h1>
<b>@userrr</b>
<p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ
あああああああああああああああああああああああああああああああああああああああ</p>
<br>
<p>福岡県</p>

app/views/tweets/edit.html.erb
<%= form_for @tweet , name: {action: :update} do |f| %>
<%= render "form", f:f%>
<% end %>

app/views/tweets/index.html.erb
<h1>ツイート</h1>
<hr>
<br>
<% @tweets.each do |tweet| %>
<p>
    <br>
    <% t2 = Time.current %>
    <% t1 = tweet.tdate %>
    <% t = t2 - t1 %>
   <%= tweet.message%>&nbsp;&nbsp;
   <%= t.ceil%><%= "秒前"%>&nbsp;&nbsp;&nbsp;
    <%= link_to '削除', "tweets/#{tweet.id}", method: :delete %>
    <%= link_to '表示', "tweets/#{tweet.id}" %>
    <%= link_to '編集', edit_tweet_path(tweet.id) %>
    <br>
</p>
<hr>

<% end %>
<p><%= link_to 'ツイート', new_tweet_path %></p>

app/views/tweets/new.html.erb
<% if flash[:notice] %>
  <p><font color="red"><span style="font-weight:bold;"><%= flash[:notice] %></font></span></p>
<% end %>

<%= form_for @tweet , name: {action: :create} do |f| %>
<%= f.label :message, 'メッセージ' %>
<%= f.text_field :message %>
<% @tweet.tdate = Time.current %>
<%= f.hidden_field :tdate %>
<%= f.submit '登録' %>
<% end %>

app/views/tweets/show.html.erb
<p>
    <strong>message：</strong>
    <%= @tweet.message %>
</p>

<p>
    <strong>tdate:</strong>
    <%= @tweet.tdate %>
</p>

<%= link_to 'Back', '/' %>